//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4214
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa només dades noves.
        /// </summary>
        internal static string ca_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ca_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat jen nová data.
        /// </summary>
        internal static string cs_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("cs_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer kun nye data.
        /// </summary>
        internal static string da_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("da_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur neue Daten importieren.
        /// </summary>
        internal static string de_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("de_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new data only.
        /// </summary>
        internal static string DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar solo datos nuevos.
        /// </summary>
        internal static string es_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("es_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuo vain uudet tiedot.
        /// </summary>
        internal static string fi_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("fi_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer seulement les nouvelles données.
        /// </summary>
        internal static string fr_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("fr_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GB580 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GB580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH505 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH505", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH615 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH615", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH625 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH625", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa solo nuovi dati.
        /// </summary>
        internal static string it_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("it_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいデータのみをインポート.
        /// </summary>
        internal static string ja_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ja_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 데이터만 가져오기.
        /// </summary>
        internal static string ko_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ko_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer alleen nieuwe data.
        /// </summary>
        internal static string nl_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("nl_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer kun nye data.
        /// </summary>
        internal static string no_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("no_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tylko nowych danych.
        /// </summary>
        internal static string pl_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("pl_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar dados novos somente.
        /// </summary>
        internal static string pt_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("pt_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт только новых данных.
        /// </summary>
        internal static string ru_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ru_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importera enbart nya data.
        /// </summary>
        internal static string sv_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("sv_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只导入新数据.
        /// </summary>
        internal static string zh_CN_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("zh_CN_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
    }
}
