//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting waypoints.
        /// </summary>
        internal static string Device_DeleteWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_DeleteWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting device info.
        /// </summary>
        internal static string Device_GetInfo_Error {
            get {
                return ResourceManager.GetString("Device_GetInfo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading waypoints.
        /// </summary>
        internal static string Device_GetWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_GetWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuficient device memory.
        /// </summary>
        internal static string Device_InsuficientMemory_Error {
            get {
                return ResourceManager.GetString("Device_InsuficientMemory_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        internal static string Device_OpenDevice_Error {
            get {
                return ResourceManager.GetString("Device_OpenDevice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending route.
        /// </summary>
        internal static string Device_SendRoute_Error {
            get {
                return ResourceManager.GetString("Device_SendRoute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending activity.
        /// </summary>
        internal static string Device_SendTrack_Error {
            get {
                return ResourceManager.GetString("Device_SendTrack_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending waypoints.
        /// </summary>
        internal static string Device_SendWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_SendWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} turned on but not connected.
        /// </summary>
        internal static string Device_TurnOnNotConnected {
            get {
                return ResourceManager.GetString("Device_TurnOnNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported by this device.
        /// </summary>
        internal static string Device_Unsupported {
            get {
                return ResourceManager.GetString("Device_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Pauses from Speed to GPS differences.
        /// </summary>
        internal static string DeviceConfigurationDlg_chkDetectPauses {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkDetectPauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import device distance info.
        /// </summary>
        internal static string DeviceConfigurationDlg_chkImportDistance {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkImportDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new data only.
        /// </summary>
        internal static string DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all device activities.
        /// </summary>
        internal static string DeviceConfigurationDlg_DeleteAllActivities {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_DeleteAllActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_16_Keymaze {
            get {
                object obj = ResourceManager.GetObject("Image_16_Keymaze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_a_rival_spoq {
            get {
                object obj = ResourceManager.GetObject("Image_48_a_rival_spoq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GB1000 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GB1000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GB580 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GB580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GH505 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH505", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GH615 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH615", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GH625 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH625", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GH625XT {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH625XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_48_GSSPORT {
            get {
                object obj = ResourceManager.GetObject("Image_48_GSSPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageDialog_Error_Title {
            get {
                return ResourceManager.GetString("MessageDialog_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        internal static string UI_Settings_DeviceConfiguration_Title {
            get {
                return ResourceManager.GetString("UI_Settings_DeviceConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting device configuration.
        /// </summary>
        internal static string UI_Settings_ExportConfig_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ExportConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        internal static string UI_Settings_ExportConfigButton_Text {
            get {
                return ResourceManager.GetString("UI_Settings_ExportConfigButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing device configuration.
        /// </summary>
        internal static string UI_Settings_ImportConfig_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file.
        /// </summary>
        internal static string UI_Settings_ImportConfig_InvalidConfiguration {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfig_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        internal static string UI_Settings_ImportConfigButton_Text {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfigButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture screen.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_CaptureScreen {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_CaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error capturing screen.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_SaveImage {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Capture.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_Title {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving image.
        /// </summary>
        internal static string UI_Settings_ScreenCaptureSave_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCaptureSave_Error", resourceCulture);
            }
        }
    }
}
