//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneFiveSoftware.SportTracks.Device.Globalsat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa només dades noves.
        /// </summary>
        internal static string ca_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ca_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importovat jen nová data.
        /// </summary>
        internal static string cs_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("cs_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer kun nye data.
        /// </summary>
        internal static string da_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("da_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur neue Daten importieren.
        /// </summary>
        internal static string de_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("de_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting waypoints.
        /// </summary>
        internal static string Device_DeleteWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_DeleteWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting device info.
        /// </summary>
        internal static string Device_GetInfo_Error {
            get {
                return ResourceManager.GetString("Device_GetInfo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading waypoints.
        /// </summary>
        internal static string Device_GetWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_GetWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insuficient memory.
        /// </summary>
        internal static string Device_InsuficientMemory_Error {
            get {
                return ResourceManager.GetString("Device_InsuficientMemory_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalsat device not found.
        /// </summary>
        internal static string Device_OpenDevice_Error {
            get {
                return ResourceManager.GetString("Device_OpenDevice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending route.
        /// </summary>
        internal static string Device_SendRoute_Error {
            get {
                return ResourceManager.GetString("Device_SendRoute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending activity.
        /// </summary>
        internal static string Device_SendTrack_Error {
            get {
                return ResourceManager.GetString("Device_SendTrack_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending waypoints.
        /// </summary>
        internal static string Device_SendWaypoints_Error {
            get {
                return ResourceManager.GetString("Device_SendWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new data only.
        /// </summary>
        internal static string DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce #Points.
        /// </summary>
        internal static string Edit_ReduceRoutePointsAction_Title {
            get {
                return ResourceManager.GetString("Edit_ReduceRoutePointsAction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar solo datos nuevos.
        /// </summary>
        internal static string es_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("es_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Globalsat device as Activity.
        /// </summary>
        internal static string Export_ExportActivityToDeviceAction_Text {
            get {
                return ResourceManager.GetString("Export_ExportActivityToDeviceAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to Globalsat device as Route.
        /// </summary>
        internal static string Export_ExportRouteToDeviceAction_Text {
            get {
                return ResourceManager.GetString("Export_ExportRouteToDeviceAction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuo vain uudet tiedot.
        /// </summary>
        internal static string fi_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("fi_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer seulement les nouvelles données.
        /// </summary>
        internal static string fr_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("fr_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints in a Globalsat Device can be managed in this plugin..
        /// </summary>
        internal static string GlobalsatDeviceCompatible {
            get {
                return ResourceManager.GetString("GlobalsatDeviceCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalsat Device plugin.
        /// </summary>
        internal static string GlobalsatDevicePluginName {
            get {
                return ResourceManager.GetString("GlobalsatDevicePluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install at least version {0} of {1} to manage waypoints in Globalsat device..
        /// </summary>
        internal static string GlobalsatDeviceToInstall {
            get {
                return ResourceManager.GetString("GlobalsatDeviceToInstall", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Image_16_Keymaze {
            get {
                object obj = ResourceManager.GetObject("Image_16_Keymaze", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GB580 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GB580", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH505 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH505", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH615 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH615", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH625 {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH625", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GH625XT {
            get {
                object obj = ResourceManager.GetObject("Image_48_GH625XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_48_GSSPORT {
            get {
                object obj = ResourceManager.GetObject("Image_48_GSSPORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa solo nuovi dati.
        /// </summary>
        internal static string it_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("it_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいデータのみをインポート.
        /// </summary>
        internal static string ja_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ja_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 새로운 데이터만 가져오기.
        /// </summary>
        internal static string ko_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ko_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageDialog_Error_Title {
            get {
                return ResourceManager.GetString("MessageDialog_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer alleen nieuwe data.
        /// </summary>
        internal static string nl_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("nl_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer kun nye data.
        /// </summary>
        internal static string no_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("no_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem communicating with {0}.
        ///Make sure that {1} is installed..
        /// </summary>
        internal static string OtherPluginExceptionText {
            get {
                return ResourceManager.GetString("OtherPluginExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected version {0} of {1}..
        /// </summary>
        internal static string OtherPluginVersion {
            get {
                return ResourceManager.GetString("OtherPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tylko nowych danych.
        /// </summary>
        internal static string pl_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("pl_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar dados novos somente.
        /// </summary>
        internal static string pt_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("pt_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт только новых данных.
        /// </summary>
        internal static string ru_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("ru_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importera enbart nya data.
        /// </summary>
        internal static string sv_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("sv_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPage_Title {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new waypoint.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_CreateWaypoint_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_CreateWaypoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_DeleteAllWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_DeleteAllWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_DeleteWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_DeleteWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_DeviceWaypoints_Title {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_DeviceWaypoints_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download waypoints from device.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_DownloadWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_DownloadWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_LocalWaypoints_Title {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_LocalWaypoints_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_OpenWaypoints_Error {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_OpenWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoints imported successfully.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_OpenWaypoints_Success {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_OpenWaypoints_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open waypoints from file.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_OpenWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_OpenWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import device waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_RefreshDeviceWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_RefreshDeviceWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving waypoints.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_SaveWaypoints_Error {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_SaveWaypoints_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected waypoints to file.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_SaveWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_SaveWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show waypoints on map.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_ShowOnMap_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_ShowOnMap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export waypoints to device.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_UploadWaypoints_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_UploadWaypoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Altitude_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Altitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Icon_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Icon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Latitude_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Latitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Longitude_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Longitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Name_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string UI_Activities_WaypointsPageControl_Waypoint_Text {
            get {
                return ResourceManager.GetString("UI_Activities_WaypointsPageControl_Waypoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export activity to Globalsat device.
        /// </summary>
        internal static string UI_ExportActivityToDeviceForm_Title {
            get {
                return ResourceManager.GetString("UI_ExportActivityToDeviceForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce points.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_ReducePoints_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_ReducePoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_Route_Name_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_Route_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr Points.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_Route_NrPoints_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_Route_NrPoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_Route_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_Route_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance per segment.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_SplitRoute_DistancePerSegment_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_SplitRoute_DistancePerSegment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_SplitRoute_None_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_SplitRoute_None_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nr Segments.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_SplitRoute_NrSegments_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_SplitRoute_NrSegments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split route into segments.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_SplitRoute_Text {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_SplitRoute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export route to Globalsat device.
        /// </summary>
        internal static string UI_ExportRouteToDeviceForm_Title {
            get {
                return ResourceManager.GetString("UI_ExportRouteToDeviceForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current nr points.
        /// </summary>
        internal static string UI_ReducePointsForm_CurrentNrPoints_Text {
            get {
                return ResourceManager.GetString("UI_ReducePointsForm_CurrentNrPoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced nr points.
        /// </summary>
        internal static string UI_ReducePointsForm_ReducedNrPoints_Text {
            get {
                return ResourceManager.GetString("UI_ReducePointsForm_ReducedNrPoints_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        internal static string UI_Settings_DeviceConfiguration_Title {
            get {
                return ResourceManager.GetString("UI_Settings_DeviceConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting device configuration.
        /// </summary>
        internal static string UI_Settings_ExportConfig_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ExportConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file.
        /// </summary>
        internal static string UI_Settings_ExportConfigButton_Text {
            get {
                return ResourceManager.GetString("UI_Settings_ExportConfigButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing device configuration.
        /// </summary>
        internal static string UI_Settings_ImportConfig_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfig_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration file.
        /// </summary>
        internal static string UI_Settings_ImportConfig_InvalidConfiguration {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfig_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from file.
        /// </summary>
        internal static string UI_Settings_ImportConfigButton_Text {
            get {
                return ResourceManager.GetString("UI_Settings_ImportConfigButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture screen.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_CaptureScreen {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_CaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error capturing screen.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_SaveImage {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Capture.
        /// </summary>
        internal static string UI_Settings_ScreenCapture_Title {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCapture_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving image.
        /// </summary>
        internal static string UI_Settings_ScreenCaptureSave_Error {
            get {
                return ResourceManager.GetString("UI_Settings_ScreenCaptureSave_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 只导入新数据.
        /// </summary>
        internal static string zh_CN_DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("zh_CN_DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
    }
}
